uerp_report:
    resource: "@UerpReportBundle/Controller/"
    type:     annotation
    prefix:   /

uerptpayment:
    resource: "@UerptpaymentBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_subcategories:
    resource: "@UerpSubcategoriesBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_main:
    resource: "@UerpMainBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_product:
    resource: "@UerpProductBundle/Controller/"
    type:     annotation
    prefix:   /

UerpProductBundle_product_unit:
    resource: "@UerpProductBundle/Resources/config/routing/productunit.yml"
    prefix:   /product_unit

uerp_product_product_icms:
    resource: "@UerpProductBundle/Resources/config/routing/producticms.yml"
    prefix:   /product_icms

uerp_supplier:
    resource: "@UerpSupplierBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_incomes:
    resource: "@UerpIncomesBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_bills:
    resource: "@UerpBillsBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_sale:
    resource: "@UerpSaleBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_customer_customer:
    resource: "@UerpCustomerBundle/Resources/config/routing/customer.yml"
    prefix:   /customer

uerp_seller:
    resource: "@UerpSellerBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_categories:
    resource: "@UerpCategoriesBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_status:
    resource: "@UerpStatusBundle/Controller/"
    type:     annotation
    prefix:   /

uerp_bank:
    resource: "@UerpBankBundle/Controller/"
    type: annotation
    prefix: /

uerp_user:
    resource: "@UerpUserBundle/Resources/config/routing.yml"
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
