uerp_user:
    resource: "@UerpUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
# app/config/routing.yml


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"